quarkus.http.port=${PORT:8080}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=banco123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bookstore
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none
